# Site settings
title: GWCC
email: montier.kess@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
permalink: /highlights/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Setup Collections
collections:
  programs:
    output: true
    permalink: /programs/:title/

  people:
    output: true
    permalink: /people/:title

  team:
    output: false

  timeline:
    output: false
